# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-06 15:01
from __future__ import unicode_literals

import colorful.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=30, unique=True, verbose_name='Sub-Identifier')),
                ('regExpr', models.CharField(blank=True, max_length=100, verbose_name='Regular expression to identify this clade without the /s')),
                ('description', tinymce.models.HTMLField(blank=True)),
                ('alignment', models.TextField(blank=True, verbose_name='Calculated Alginment for all alignment members')),
                ('alignment_date', models.TextField(default=django.utils.timezone.now, verbose_name='last calculated alignment')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.clade')),
            ],
        ),
        migrations.CreateModel(
            name='feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Col1 domain', max_length=50)),
                ('description', tinymce.models.HTMLField(blank=True)),
                ('region', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalidRegion', message='Please enter the region in the format 12..34,24..45', regex='((\\d+\\.\\.\\d+),){0,}(\\d+\\.\\.\\d+)')])),
            ],
        ),
        migrations.CreateModel(
            name='feature_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', tinymce.models.HTMLField(blank=True)),
                ('color', colorful.fields.RGBColorField()),
                ('style', models.CharField(blank=True, max_length=50)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.feature_type')),
            ],
        ),
        migrations.CreateModel(
            name='gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_id', models.CharField(max_length=20, verbose_name='Gene id in entrzez')),
                ('wormbase_id', models.CharField(max_length=100)),
                ('prot_id', models.CharField(max_length=20, verbose_name='UniProt Id')),
                ('last_changed', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last changed')),
                ('sequence', models.CharField(max_length=5000, verbose_name='Amino acid sequence')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='My official gene name')),
                ('alias', models.CharField(blank=True, max_length=100, verbose_name='Aliases')),
                ('description', tinymce.models.HTMLField(blank=True)),
                ('clade', models.ManyToManyField(blank=True, null=True, to='database.clade')),
            ],
        ),
        migrations.AddField(
            model_name='feature',
            name='gene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.gene'),
        ),
        migrations.AddField(
            model_name='feature',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.feature_type'),
        ),
    ]
