# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-06 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clade',
            name='identifier',
            field=models.CharField(max_length=31, unique=True, verbose_name='Sub-Identifier'),
        ),
    ]
