# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-06 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20171106_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='prot_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='UniProt Id'),
        ),
        migrations.AlterField(
            model_name='gene',
            name='wormbase_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
