# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20171106_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_key', models.CharField(max_length=40, unique=True, verbose_name='Setting key')),
                ('s_value', models.CharField(max_length=256, verbose_name='Setting value')),
            ],
        ),
    ]
