# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-23 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_project_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='manually_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feature',
            name='modeOfGeneration',
            field=models.CharField(choices=[('PF', 'PFAM'), ('SP', 'SignalP'), ('RX', 'Regular Expressions'), ('MN', 'manual')], default='RX', max_length=2),
        ),
    ]
