# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-12 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20180223_2042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clade',
            options={'ordering': ['identifier']},
        ),
        migrations.AlterModelOptions(
            name='gene',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='clade',
            name='model_gene',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_clade', to='database.gene'),
        ),
        migrations.AlterField(
            model_name='gene',
            name='gene_id',
            field=models.CharField(max_length=20, verbose_name='Gene id in entrez'),
        ),
    ]
