# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-12 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20180312_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clade',
            name='model_gene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_clade', to='database.gene'),
        ),
    ]
