# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-19 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20180312_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature_type',
            name='domain_list',
            field=models.BooleanField(default=True),
        ),
    ]
