# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-19 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_feature_type_domain_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature_type',
            name='pfam_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
