# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-20 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_feature_type_pfam_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='modeOfGeneration',
            field=models.CharField(choices=[('PF', 'PFAM'), ('SP', 'SignalP'), ('RX', 'Regular Expressions'), ('PI', 'Philius Webserver'), ('MN', 'manual')], default='RX', max_length=2),
        ),
    ]
