# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-26 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20180320_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature_type',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
