# Generated by Django 2.0.5 on 2018-07-11 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_auto_20180326_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clade',
            name='model_gene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_clade', to='database.gene'),
        ),
    ]
