# Generated by Django 2.0.5 on 2018-07-12 08:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_auto_20180711_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='transcript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=31, unique=True, verbose_name='Transcript identifier')),
                ('description', tinymce.models.HTMLField(blank=True)),
                ('chromosome', models.CharField(max_length=10, unique=True, verbose_name='Chromosome')),
                ('region', models.CharField(max_length=10000, validators=[django.core.validators.RegexValidator(code='invalidRegion', message='Please enter the region in the format 12..34,24..45', regex='((\\d+\\.\\.\\d+),){0,}(\\d+\\.\\.\\d+)')])),
                ('model_gene', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_transcript', to='database.gene')),
            ],
        ),
    ]
