# Generated by Django 2.0.5 on 2018-07-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_transcript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcript',
            name='chromosome',
            field=models.CharField(max_length=10, verbose_name='Chromosome'),
        ),
    ]
