"""
Django settings for cutDB project.

Generated by 'django-admin startproject' using Django 1.11.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
from .base import *

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '****set a default key here****')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False # You might want to switch this one?
DEBUG = bool( os.environ.get('DJANGO_DEBUG', False) )

ALLOWED_HOSTS = ["*** set you hosts here ***"]
# Use "triple quotes" to escape whitespaces in windows paths e.g: '"c:\Program Files\clustalO\clustalo.exe"'
CLUSTALO_BIN ="*** set to full path + executable of ClustalO binary ***"

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'cutdb',
        'USER': '***db_user***',
        'PASSWORD': '***db_password***',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        
    }
}

STATIC_URL = '/static/'  
STATIC_ROOT = "***your static root***"
