# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature_type',
            name='style',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
