# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20170822_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clade',
            name='identifier',
            field=models.CharField(max_length=6, unique=True, verbose_name='Sub-Identifier'),
        ),
    ]
