# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 10:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20170822_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='last_changed',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 24, 10, 59, 10, 195753, tzinfo=utc), verbose_name='last changed'),
        ),
    ]
