# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 11:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20170824_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='last_changed',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 24, 11, 0, 33, 438746, tzinfo=utc), verbose_name='last changed'),
        ),
    ]
