# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20170824_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='last_changed',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last changed'),
        ),
    ]
