# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20170824_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='gene_id',
            field=models.CharField(max_length=20, verbose_name='Gene id in entrzez'),
        ),
        migrations.AlterField(
            model_name='gene',
            name='prot_id',
            field=models.CharField(max_length=20, verbose_name='UniProt Id'),
        ),
    ]
