# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20170824_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature_type',
            old_name='type',
            new_name='name',
        ),
    ]
