# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_auto_20170831_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='clade',
            name='alignment',
            field=models.TextField(blank=True, verbose_name='Calculated Alginment for all alignment members'),
        ),
        migrations.AddField(
            model_name='clade',
            name='alignment_date',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='last calculated alignment'),
        ),
    ]
